name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: pip install -r tests/requirements.txt
    - name: change dir [tests]
      run: cd tests
    - name: run tests
      run: |
            python builder.py
            pytest -svv
    - name: upload to coverallz
      run:  cpp-coveralls
